// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Aplicacion
{
    public int IdAplicacion { get; set; }

    public string Nombre { get; set; }

    public int IdProducto { get; set; }

    public Guid Token { get; set; }

    public short Tipo { get; set; }

    public bool Directo { get; set; }

    public bool? Onboarding { get; set; }

    public string PlantillaCorreoVerificacion { get; set; }

    public string IpIngreso { get; set; }

    public string UsuarioIngreso { get; set; }

    public DateTime FechaIngreso { get; set; }

    public string IpModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public short IdEstado { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }

    public virtual ICollection<Modulo> Modulo { get; set; } = new List<Modulo>();

    public virtual ICollection<Perfil> Perfil { get; set; } = new List<Perfil>();

    public virtual ICollection<Sesion> Sesion { get; set; } = new List<Sesion>();

    public virtual ICollection<UsuarioUnidad> UsuarioUnidad { get; set; } = new List<UsuarioUnidad>();
}