// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class AuditLogs
{
    public long Id { get; set; }

    public string InicioSesion { get; set; }

    public string IdUsuario { get; set; }

    public int? IdAplicacion { get; set; }

    public string Browser { get; set; }

    public string IpAddress { get; set; }

    public string Exception { get; set; }

    public int? ExecutionDuration { get; set; }

    public DateTime? ExecutionDate { get; set; }

    public string MethodName { get; set; }

    public string Parameters { get; set; }

    public string ServiceName { get; set; }

    public string ExceptionMessage { get; set; }
}