// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class DetallePerfil
{
    public long IdDetallePerfil { get; set; }

    public Guid IdPerfil { get; set; }

    public int IdModulo { get; set; }

    public long IdOpcion { get; set; }

    public string Permisos { get; set; }

    public string IpIngreso { get; set; }

    public string UsuarioIngreso { get; set; }

    public DateTime FechaIngreso { get; set; }

    public string IpModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public short IdEstado { get; set; }

    public virtual Modulo IdModuloNavigation { get; set; }

    public virtual Opcion IdOpcionNavigation { get; set; }

    public virtual Perfil IdPerfilNavigation { get; set; }
}