// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Empresa
{
    public int IdEmpresa { get; set; }

    public string Ruc { get; set; }

    public string RazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public string CodigoSbs { get; set; }

    public string Pais { get; set; }

    public string Moneda { get; set; }

    public string UrlLogo { get; set; }

    public string Siglas { get; set; }

    public Guid Token { get; set; }

    public bool Aplicacion { get; set; }

    public string Utc { get; set; }

    public string Email { get; set; }

    public string Direccion { get; set; }

    public string IpIngreso { get; set; }

    public string UsuarioIngreso { get; set; }

    public DateTime FechaIngreso { get; set; }

    public string IpModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public short IdEstado { get; set; }

    public virtual ICollection<ProductoEmpresa> ProductoEmpresa { get; set; } = new List<ProductoEmpresa>();

    public virtual ICollection<UnidadAdmin> UnidadAdmin { get; set; } = new List<UnidadAdmin>();

    public virtual ICollection<UsuarioUnidad> UsuarioUnidad { get; set; } = new List<UsuarioUnidad>();
}