// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Opcion
{
    public long IdOpcion { get; set; }

    public int IdModulo { get; set; }

    public int Orden { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string Icono { get; set; }

    public string Accion { get; set; }

    public string Operaciones { get; set; }

    public string Ayuda { get; set; }

    public string IpIngreso { get; set; }

    /// <summary>
    /// Usuario que ingreso la informacion
    /// </summary>
    public string UsuarioIngreso { get; set; }

    /// <summary>
    /// fecha de ingreso de la informacion
    /// </summary>
    public DateTime FechaIngreso { get; set; }

    /// <summary>
    /// ip o Nombre de la PC donde se modifica la informacion
    /// </summary>
    public string IpModificacion { get; set; }

    /// <summary>
    /// Usuario que modifica la informacion
    /// </summary>
    public string UsuarioModificacion { get; set; }

    /// <summary>
    /// fecha de modificacion de la informacion
    /// </summary>
    public DateTime? FechaModificacion { get; set; }

    /// <summary>
    /// Estado del Registro
    /// </summary>
    public short IdEstado { get; set; }

    public virtual ICollection<DetallePerfil> DetallePerfil { get; set; } = new List<DetallePerfil>();

    public virtual Modulo IdModuloNavigation { get; set; }
}