// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Perfil
{
    public Guid IdPerfil { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public int IdTipoPerfil { get; set; }

    public int IdProducto { get; set; }

    public int IdAplicacion { get; set; }

    public string IpIngreso { get; set; }

    public string UsuarioIngreso { get; set; }

    public DateTime FechaIngreso { get; set; }

    public string IpModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public short IdEstado { get; set; }

    public virtual ICollection<DetallePerfil> DetallePerfil { get; set; } = new List<DetallePerfil>();

    public virtual Aplicacion IdAplicacionNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }

    public virtual TipoPerfil IdTipoPerfilNavigation { get; set; }

    public virtual ICollection<UsuarioUnidad> UsuarioUnidad { get; set; } = new List<UsuarioUnidad>();
}