// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class ProductoEmpresa
{
    public long IdProductoEmpresa { get; set; }

    public Guid? IdLicencia { get; set; }

    public int IdEmpresa { get; set; }

    public int IdProducto { get; set; }

    public DateTime FechaActivacion { get; set; }

    public DateTime? FechaExpiracion { get; set; }

    public virtual Empresa IdEmpresaNavigation { get; set; }

    public virtual Licencia IdLicenciaNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }
}