// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Sesion
{
    public Guid IdSesion { get; set; }

    public DateTime Fecha { get; set; }

    public string InicioSesion { get; set; }

    public bool Exitoso { get; set; }

    public string Mensaje { get; set; }

    public string IdUsuario { get; set; }

    public int? IdAplicacion { get; set; }

    public string Error { get; set; }

    public byte[] Codebase { get; set; }

    public string DeviceId { get; set; }

    public string Latitud { get; set; }

    public string Longitud { get; set; }

    public string Estado { get; set; }

    public virtual Aplicacion IdAplicacionNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}