// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class UnidadAdmin
{
    public int IdUnidadAdmin { get; set; }

    public int IdEmpresa { get; set; }

    public int IdTipoUnidadAdmin { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public Guid Token { get; set; }

    public string IpIngreso { get; set; }

    public string UsuarioIngreso { get; set; }

    public DateTime FechaIngreso { get; set; }

    public string IpModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public short IdEstado { get; set; }

    public virtual Empresa IdEmpresaNavigation { get; set; }

    public virtual TipoUnidadAdmin IdTipoUnidadAdminNavigation { get; set; }

    public virtual ICollection<UsuarioUnidad> UsuarioUnidad { get; set; } = new List<UsuarioUnidad>();
}