// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Usuario
{
    public string IdUsuario { get; set; }

    public string InicioSesion { get; set; }

    public string Identificacion { get; set; }

    public string Ruc { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Correo { get; set; }

    public string Telefono { get; set; }

    public Guid Token { get; set; }

    public string Foto { get; set; }

    public int IdProducto { get; set; }

    public bool IdEstado { get; set; }

    public virtual ICollection<Sesion> Sesion { get; set; } = new List<Sesion>();

    public virtual ICollection<UsuarioUnidad> UsuarioUnidad { get; set; } = new List<UsuarioUnidad>();
}