// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class UsuarioUnidad
{
    public long IdUsuarioUnidad { get; set; }

    public string IdUsuario { get; set; }

    public int IdEmpresa { get; set; }

    public Guid IdPerfil { get; set; }

    public int? IdUnidadAdmin { get; set; }

    public int IdAplicacion { get; set; }

    public bool Activo { get; set; }

    public virtual Aplicacion IdAplicacionNavigation { get; set; }

    public virtual Empresa IdEmpresaNavigation { get; set; }

    public virtual Perfil IdPerfilNavigation { get; set; }

    public virtual UnidadAdmin IdUnidadAdminNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}