// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    public partial class VerifyUserEmailV2Result
    {
        public bool? Success { get; set; }
        public int StatusCode { get; set; }
        public string Message { get; set; }
    }
}
