// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace DataAccess.Repositories;

public partial class AuthContext : DbContext
{
    public AuthContext(DbContextOptions<AuthContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Aplicacion> Aplicacion { get; set; }

    public virtual DbSet<AuditLogs> AuditLogs { get; set; }

    public virtual DbSet<DetallePerfil> DetallePerfil { get; set; }

    public virtual DbSet<Empresa> Empresa { get; set; }

    public virtual DbSet<Licencia> Licencia { get; set; }

    public virtual DbSet<Modulo> Modulo { get; set; }

    public virtual DbSet<Opcion> Opcion { get; set; }

    public virtual DbSet<Perfil> Perfil { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<ProductoEmpresa> ProductoEmpresa { get; set; }

    public virtual DbSet<Sesion> Sesion { get; set; }

    public virtual DbSet<TipoPerfil> TipoPerfil { get; set; }

    public virtual DbSet<TipoUnidadAdmin> TipoUnidadAdmin { get; set; }

    public virtual DbSet<UnidadAdmin> UnidadAdmin { get; set; }

    public virtual DbSet<UserMailVerify> UserMailVerify { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<UsuarioUnidad> UsuarioUnidad { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AplicacionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AuditLogsConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DetallePerfilConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmpresaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LicenciaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ModuloConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.OpcionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PerfilConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductoEmpresaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SesionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoPerfilConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoUnidadAdminConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UnidadAdminConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserMailVerifyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuarioUnidadConfiguration());

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
