// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class AplicacionConfiguration : IEntityTypeConfiguration<Aplicacion>
    {
        public void Configure(EntityTypeBuilder<Aplicacion> entity)
        {
            entity.HasKey(e => e.IdAplicacion);

            entity.HasIndex(e => e.IdAplicacion, "UK_Aplicacion_Token").IsUnique();

            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.IdEstado).HasDefaultValueSql("((1))");
            entity.Property(e => e.IpIngreso)
            .IsRequired()
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.IpModificacion)
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.Nombre)
            .IsRequired()
            .HasMaxLength(200)
            .IsUnicode(false)
            .HasDefaultValueSql("(newid())");
            entity.Property(e => e.PlantillaCorreoVerificacion)
            .HasMaxLength(20)
            .IsUnicode(false);
            entity.Property(e => e.Tipo).HasDefaultValueSql("((1))");
            entity.Property(e => e.Token).HasDefaultValueSql("(newid())");
            entity.Property(e => e.UsuarioIngreso)
            .IsRequired()
            .HasMaxLength(150)
            .IsUnicode(false);
            entity.Property(e => e.UsuarioModificacion)
            .HasMaxLength(200)
            .IsUnicode(false);

            entity.HasOne(d => d.IdProductoNavigation).WithMany(p => p.Aplicacion)
            .HasForeignKey(d => d.IdProducto)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Aplicacion_Producto");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Aplicacion> entity);
    }
}
