// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class AuditLogsConfiguration : IEntityTypeConfiguration<AuditLogs>
    {
        public void Configure(EntityTypeBuilder<AuditLogs> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_AbpAuditLogs");

            entity.Property(e => e.Browser).HasMaxLength(512);
            entity.Property(e => e.Exception).HasMaxLength(2000);
            entity.Property(e => e.ExceptionMessage)
            .HasMaxLength(1024)
            .IsUnicode(false);
            entity.Property(e => e.ExecutionDate).HasColumnType("datetime");
            entity.Property(e => e.IdUsuario)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.InicioSesion)
            .HasMaxLength(200)
            .IsUnicode(false);
            entity.Property(e => e.IpAddress).HasMaxLength(64);
            entity.Property(e => e.MethodName)
            .HasMaxLength(256)
            .IsUnicode(false);
            entity.Property(e => e.Parameters)
            .HasMaxLength(1024)
            .IsUnicode(false);
            entity.Property(e => e.ServiceName)
            .HasMaxLength(256)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AuditLogs> entity);
    }
}
