// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class DetallePerfilConfiguration : IEntityTypeConfiguration<DetallePerfil>
    {
        public void Configure(EntityTypeBuilder<DetallePerfil> entity)
        {
            entity.HasKey(e => e.IdDetallePerfil);

            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.IdEstado).HasDefaultValueSql("((1))");
            entity.Property(e => e.IpIngreso)
            .IsRequired()
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.IpModificacion)
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.Permisos)
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.UsuarioIngreso)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.UsuarioModificacion)
            .HasMaxLength(50)
            .IsUnicode(false);

            entity.HasOne(d => d.IdModuloNavigation).WithMany(p => p.DetallePerfil)
            .HasForeignKey(d => d.IdModulo)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_DetallePerfil_Modulo");

            entity.HasOne(d => d.IdOpcionNavigation).WithMany(p => p.DetallePerfil)
            .HasForeignKey(d => d.IdOpcion)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_DetallePerfil_Opcion");

            entity.HasOne(d => d.IdPerfilNavigation).WithMany(p => p.DetallePerfil)
            .HasForeignKey(d => d.IdPerfil)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_DetallePerfil_Perfil");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DetallePerfil> entity);
    }
}
