// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class EmpresaConfiguration : IEntityTypeConfiguration<Empresa>
    {
        public void Configure(EntityTypeBuilder<Empresa> entity)
        {
            entity.HasKey(e => e.IdEmpresa);

            entity.HasIndex(e => e.Token, "UK_Empresa_TOKEN").IsUnique();

            entity.Property(e => e.CodigoSbs)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("CodigoSBS");
            entity.Property(e => e.Direccion)
            .HasMaxLength(200)
            .IsUnicode(false);
            entity.Property(e => e.Email)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.IpIngreso)
            .IsRequired()
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.IpModificacion)
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.Moneda)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.NombreComercial)
            .HasMaxLength(1000)
            .IsUnicode(false);
            entity.Property(e => e.Pais)
            .HasMaxLength(200)
            .IsUnicode(false);
            entity.Property(e => e.RazonSocial)
            .IsRequired()
            .HasMaxLength(1000)
            .IsUnicode(false);
            entity.Property(e => e.Ruc)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("RUC");
            entity.Property(e => e.Siglas)
            .HasMaxLength(5)
            .IsUnicode(false);
            entity.Property(e => e.Token).HasDefaultValueSql("(newid())");
            entity.Property(e => e.UrlLogo)
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.UsuarioIngreso)
            .IsRequired()
            .HasMaxLength(150)
            .IsUnicode(false);
            entity.Property(e => e.UsuarioModificacion)
            .HasMaxLength(200)
            .IsUnicode(false);
            entity.Property(e => e.Utc)
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("UTC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Empresa> entity);
    }
}
