// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class ModuloConfiguration : IEntityTypeConfiguration<Modulo>
    {
        public void Configure(EntityTypeBuilder<Modulo> entity)
        {
            entity.HasKey(e => e.IdModulo);

            entity.Property(e => e.Codigo)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false);
            entity.Property(e => e.Descripcion)
            .IsRequired()
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.Icono)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.IpIngreso)
            .IsRequired()
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.IpModificacion)
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.UsuarioIngreso)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.UsuarioModificacion)
            .HasMaxLength(50)
            .IsUnicode(false);

            entity.HasOne(d => d.IdAplicacionNavigation).WithMany(p => p.Modulo)
            .HasForeignKey(d => d.IdAplicacion)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Modulo_Aplicacion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Modulo> entity);
    }
}
