// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class OpcionConfiguration : IEntityTypeConfiguration<Opcion>
    {
        public void Configure(EntityTypeBuilder<Opcion> entity)
        {
            entity.HasKey(e => e.IdOpcion);

            entity.Property(e => e.Accion)
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.Ayuda)
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.Descripcion)
            .HasMaxLength(150)
            .IsUnicode(false);
            entity.Property(e => e.FechaIngreso)
            .HasComment("fecha de ingreso de la informacion")
            .HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion)
            .HasComment("fecha de modificacion de la informacion")
            .HasColumnType("datetime");
            entity.Property(e => e.Icono)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.IdEstado).HasComment("Estado del Registro");
            entity.Property(e => e.IpIngreso)
            .IsRequired()
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.IpModificacion)
            .HasMaxLength(15)
            .IsUnicode(false)
            .HasComment("ip o Nombre de la PC donde se modifica la informacion");
            entity.Property(e => e.Nombre)
            .IsRequired()
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.Operaciones)
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.Orden).HasDefaultValueSql("((1))");
            entity.Property(e => e.UsuarioIngreso)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasComment("Usuario que ingreso la informacion");
            entity.Property(e => e.UsuarioModificacion)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasComment("Usuario que modifica la informacion");

            entity.HasOne(d => d.IdModuloNavigation).WithMany(p => p.Opcion)
            .HasForeignKey(d => d.IdModulo)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Opcion_Modulo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Opcion> entity);
    }
}
