// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class UnidadAdminConfiguration : IEntityTypeConfiguration<UnidadAdmin>
    {
        public void Configure(EntityTypeBuilder<UnidadAdmin> entity)
        {
            entity.HasKey(e => e.IdUnidadAdmin);

            entity.Property(e => e.Codigo)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false);
            entity.Property(e => e.Descripcion)
            .IsRequired()
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.Direccion)
            .IsRequired()
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");
            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.IpIngreso)
            .IsRequired()
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.IpModificacion)
            .HasMaxLength(15)
            .IsUnicode(false);
            entity.Property(e => e.Telefono)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Token).HasDefaultValueSql("(newid())");
            entity.Property(e => e.UsuarioIngreso)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.UsuarioModificacion)
            .HasMaxLength(50)
            .IsUnicode(false);

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.UnidadAdmin)
            .HasForeignKey(d => d.IdEmpresa)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_UnidadAdmin_Empresa");

            entity.HasOne(d => d.IdTipoUnidadAdminNavigation).WithMany(p => p.UnidadAdmin)
            .HasForeignKey(d => d.IdTipoUnidadAdmin)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_UnidadAdmin_TipoUnidadAdmin");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UnidadAdmin> entity);
    }
}
