// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class UserMailVerifyConfiguration : IEntityTypeConfiguration<UserMailVerify>
    {
        public void Configure(EntityTypeBuilder<UserMailVerify> entity)
        {
            entity.Property(e => e.Correo)
            .IsRequired()
            .HasMaxLength(200)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserMailVerify> entity);
    }
}
