// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class UsuarioConfiguration : IEntityTypeConfiguration<Usuario>
    {
        public void Configure(EntityTypeBuilder<Usuario> entity)
        {
            entity.HasKey(e => e.IdUsuario);

            entity.HasIndex(e => e.IdUsuario, "UK_Usuario").IsUnique();

            entity.HasIndex(e => e.Token, "UK_Usuario_Token").IsUnique();

            entity.Property(e => e.IdUsuario)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Apellido)
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.Correo)
            .IsRequired()
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.Foto)
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.Identificacion)
            .IsRequired()
            .HasMaxLength(20)
            .IsUnicode(false);
            entity.Property(e => e.InicioSesion)
            .IsRequired()
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.Nombre)
            .IsRequired()
            .HasMaxLength(500)
            .IsUnicode(false);
            entity.Property(e => e.Ruc)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasDefaultValueSql("('N/A')");
            entity.Property(e => e.Telefono)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Token).HasDefaultValueSql("(newid())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Usuario> entity);
    }
}
