// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConcentratorFraud.DataAccess.Models;
using ConcentratorFraud.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Repositories.Configurations
{
    public partial class ActivoIncidenteConfiguration : IEntityTypeConfiguration<ActivoIncidente>
    {
        public void Configure(EntityTypeBuilder<ActivoIncidente> entity)
        {
            entity.HasKey(e => e.IdActivoIncidente);

            entity.Property(e => e.IdActivoIncidente).ValueGeneratedNever();
            entity.Property(e => e.NombreActivo)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.SerialActivo)
            .HasMaxLength(100)
            .IsUnicode(false);

            entity.HasOne(d => d.IdActivoIncidenteNavigation).WithOne(p => p.ActivoIncidente)
            .HasForeignKey<ActivoIncidente>(d => d.IdActivoIncidente)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ActivoIncidente_Incidente");

            entity.HasOne(d => d.IdTipoActivoAfectadoNavigation).WithMany(p => p.ActivoIncidente)
            .HasForeignKey(d => d.IdTipoActivoAfectado)
            .HasConstraintName("FK_ActivoIncidente_TipoActivoAfectado");

            entity.HasOne(d => d.IdTipoActivoNoAfectadoNavigation).WithMany(p => p.ActivoIncidente)
            .HasForeignKey(d => d.IdTipoActivoNoAfectado)
            .HasConstraintName("FK_ActivoIncidente_TipoActivoNoAfectado");

            entity.HasOne(d => d.IdTipoActivoObjectivoNavigation).WithMany(p => p.ActivoIncidente)
            .HasForeignKey(d => d.IdTipoActivoObjectivo)
            .HasConstraintName("FK_ActivoIncidente_TipoActivoObjectivo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ActivoIncidente> entity);
    }
}
