// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConcentratorFraud.DataAccess.Models;
using ConcentratorFraud.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Repositories.Configurations
{
    public partial class AdvanceIocConfiguration : IEntityTypeConfiguration<AdvanceIoc>
    {
        public void Configure(EntityTypeBuilder<AdvanceIoc> entity)
        {
            entity.HasKey(e => e.IdAdvanceIoc);

            entity.ToTable("AdvanceIOC");

            entity.Property(e => e.IdAdvanceIoc).HasColumnName("IdAdvanceIOC");
            entity.Property(e => e.ActividadInusual).IsUnicode(false);
            entity.Property(e => e.AlgoritmoRegional).IsUnicode(false);
            entity.Property(e => e.AutorunsRegistry)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.MerchantId)
            .HasMaxLength(20)
            .IsUnicode(false)
            .HasColumnName("MerchantID");
            entity.Property(e => e.PatronAnomalo).IsUnicode(false);
            entity.Property(e => e.PatronTrafico).IsUnicode(false);
            entity.Property(e => e.RedAdquirencia)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.TerminalId)
            .HasMaxLength(20)
            .IsUnicode(false)
            .HasColumnName("TerminalID");
            entity.Property(e => e.YaraRule).IsUnicode(false);

            entity.HasOne(d => d.IdIncidenteNavigation).WithMany(p => p.AdvanceIoc)
            .HasForeignKey(d => d.IdIncidente)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_AdvanceIOC_Incidente");

            entity.HasOne(d => d.IdIntentosInicioSesionNavigation).WithMany(p => p.AdvanceIoc)
            .HasForeignKey(d => d.IdIntentosInicioSesion)
            .HasConstraintName("FK_AdvanceIOC_IntentosInicioSesion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AdvanceIoc> entity);
    }
}
