// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConcentratorFraud.DataAccess.Models;
using ConcentratorFraud.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Repositories.Configurations
{
    public partial class CategoriaIncidenteConfiguration : IEntityTypeConfiguration<CategoriaIncidente>
    {
        public void Configure(EntityTypeBuilder<CategoriaIncidente> entity)
        {
            entity.HasKey(e => e.IdCategoriaIncidente);

            entity.Property(e => e.Descripcion)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);

            entity.HasOne(d => d.IdTipoIncidenteNavigation).WithMany(p => p.CategoriaIncidente)
            .HasForeignKey(d => d.IdTipoIncidente)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_CategoriaIncidente_TipoIncidente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CategoriaIncidente> entity);
    }
}
