// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConcentratorFraud.DataAccess.Models;
using ConcentratorFraud.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Repositories.Configurations
{
    public partial class CiudadLocalizacionConfiguration : IEntityTypeConfiguration<CiudadLocalizacion>
    {
        public void Configure(EntityTypeBuilder<CiudadLocalizacion> entity)
        {
            entity.HasKey(e => e.IdCiudadLocalizacion);

            entity.Property(e => e.IdCiudadLocalizacion).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CiudadLocalizacion> entity);
    }
}
