// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConcentratorFraud.DataAccess.Models;
using ConcentratorFraud.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Repositories.Configurations
{
    public partial class PaisLocalizacionConfiguration : IEntityTypeConfiguration<PaisLocalizacion>
    {
        public void Configure(EntityTypeBuilder<PaisLocalizacion> entity)
        {
            entity.HasKey(e => e.IdPaisLocalizacion);

            entity.Property(e => e.IdPaisLocalizacion).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PaisLocalizacion> entity);
    }
}
