// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConcentratorFraud.DataAccess.Models;
using ConcentratorFraud.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Repositories.Configurations
{
    public partial class PrincipalIocConfiguration : IEntityTypeConfiguration<PrincipalIoc>
    {
        public void Configure(EntityTypeBuilder<PrincipalIoc> entity)
        {
            entity.HasKey(e => e.IdPrincipalIoc).HasName("PK_DetallePrincipalIOC");

            entity.ToTable("PrincipalIOC");

            entity.Property(e => e.IdPrincipalIoc).HasColumnName("IdPrincipalIOC");
            entity.Property(e => e.ArchivoDocumento)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.ArchivoSo)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("ArchivoSO");
            entity.Property(e => e.DireccionIp)
            .HasMaxLength(20)
            .IsUnicode(false);
            entity.Property(e => e.DireccionWeb)
            .HasMaxLength(200)
            .IsUnicode(false);
            entity.Property(e => e.Dominio)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.Hashes)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.NombrePs)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("NombrePS");
            entity.Property(e => e.ServidorIp)
            .HasMaxLength(20)
            .IsUnicode(false);

            entity.HasOne(d => d.IdIncidenteNavigation).WithMany(p => p.PrincipalIoc)
            .HasForeignKey(d => d.IdIncidente)
            .HasConstraintName("FK_PrincipalIOC_Incidente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PrincipalIoc> entity);
    }
}
