// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConcentratorFraud.DataAccess.Models;
using ConcentratorFraud.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Repositories.Configurations
{
    public partial class RecomendacionConfiguration : IEntityTypeConfiguration<Recomendacion>
    {
        public void Configure(EntityTypeBuilder<Recomendacion> entity)
        {
            entity.HasKey(e => e.IdRecomendacion);

            entity.Property(e => e.Recomendacion1)
            .IsRequired()
            .IsUnicode(false)
            .HasColumnName("Recomendacion");

            entity.HasOne(d => d.IdIncidenteNavigation).WithMany(p => p.Recomendacion)
            .HasForeignKey(d => d.IdIncidente)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Recomendacion_Incidente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Recomendacion> entity);
    }
}
