// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConcentratorFraud.DataAccess.Models;
using ConcentratorFraud.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Repositories.Configurations
{
    public partial class RiesgoIndicadorConfiguration : IEntityTypeConfiguration<RiesgoIndicador>
    {
        public void Configure(EntityTypeBuilder<RiesgoIndicador> entity)
        {
            entity.HasKey(e => e.IdRiesgoIndicador);

            entity.Property(e => e.IdRiesgoIndicador).ValueGeneratedNever();
            entity.Property(e => e.Mensaje)
            .HasMaxLength(300)
            .IsUnicode(false);

            entity.HasOne(d => d.IdIncidenteNavigation).WithMany(p => p.RiesgoIndicador)
            .HasForeignKey(d => d.IdIncidente)
            .HasConstraintName("FK_RiesgoIndicador_Incidente");

            entity.HasOne(d => d.IdTipoAlertaNavigation).WithMany(p => p.RiesgoIndicador)
            .HasForeignKey(d => d.IdTipoAlerta)
            .HasConstraintName("FK_RiesgoIndicador_TipoAlerta");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RiesgoIndicador> entity);
    }
}
