// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Models;

public partial class ActivoIncidente
{
    public int IdActivoIncidente { get; set; }

    public int IdIncidente { get; set; }

    public string NombreActivo { get; set; }

    public string SerialActivo { get; set; }

    public int? IdTipoActivoObjectivo { get; set; }

    public int? IdTipoActivoAfectado { get; set; }

    public int? IdTipoActivoNoAfectado { get; set; }

    public virtual Incidente IdActivoIncidenteNavigation { get; set; }

    public virtual TipoActivoAfectado IdTipoActivoAfectadoNavigation { get; set; }

    public virtual TipoActivoNoAfectado IdTipoActivoNoAfectadoNavigation { get; set; }

    public virtual TipoActivoObjectivo IdTipoActivoObjectivoNavigation { get; set; }
}