// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Models;

public partial class AdvanceIoc
{
    public long IdAdvanceIoc { get; set; }

    public int IdIncidente { get; set; }

    public string AutorunsRegistry { get; set; }

    public string YaraRule { get; set; }

    public string MerchantId { get; set; }

    public string TerminalId { get; set; }

    public string RedAdquirencia { get; set; }

    public string PatronTrafico { get; set; }

    public string PatronAnomalo { get; set; }

    public string AlgoritmoRegional { get; set; }

    public string ActividadInusual { get; set; }

    public int? IdIntentosInicioSesion { get; set; }

    public bool Activo { get; set; }

    public virtual Incidente IdIncidenteNavigation { get; set; }

    public virtual IntentosInicioSesion IdIntentosInicioSesionNavigation { get; set; }
}