// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Models;

public partial class Incidente
{
    public int IdIncidente { get; set; }

    public int? IdTipoIncidente { get; set; }

    public int? IdCategoriaIncidente { get; set; }

    public int? IdPaisInstitucion { get; set; }

    public int? IdPaisLocalizacion { get; set; }

    public int? IdCiudadLocalizacion { get; set; }

    public DateTime? FechaHora { get; set; }

    public int? IdModoIncidente { get; set; }

    public string VulnerabilidadCve { get; set; }

    public int? IdNivelCriticidad { get; set; }

    public int? IdNivelImpactoActual { get; set; }

    public int? IdNivelImpactoEsperado { get; set; }

    public decimal? NivelPrioridad { get; set; }

    public int? IdDesignacionTlp { get; set; }

    public string Descripcion { get; set; }

    public string Referencias { get; set; }

    public DateTime FechaHoraRegistro { get; set; }

    public string UsuarioRegistro { get; set; }

    public string IpRegistro { get; set; }

    public DateTime? FechaHoraModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? IpModificacion { get; set; }

    public bool Activo { get; set; }

    public virtual ActivoIncidente ActivoIncidente { get; set; }

    public virtual ICollection<AdvanceIoc> AdvanceIoc { get; set; } = new List<AdvanceIoc>();

    public virtual CategoriaIncidente IdCategoriaIncidenteNavigation { get; set; }

    public virtual CiudadLocalizacion IdCiudadLocalizacionNavigation { get; set; }

    public virtual DesignacionTlp IdDesignacionTlpNavigation { get; set; }

    public virtual ModoIncidente IdModoIncidenteNavigation { get; set; }

    public virtual NivelCriticidad IdNivelCriticidadNavigation { get; set; }

    public virtual NivelImpactoActual IdNivelImpactoActualNavigation { get; set; }

    public virtual NivelImpactoEsperado IdNivelImpactoEsperadoNavigation { get; set; }

    public virtual PaisInstitucion IdPaisInstitucionNavigation { get; set; }

    public virtual PaisLocalizacion IdPaisLocalizacionNavigation { get; set; }

    public virtual TipoIncidente IdTipoIncidenteNavigation { get; set; }

    public virtual ICollection<PrincipalIoc> PrincipalIoc { get; set; } = new List<PrincipalIoc>();

    public virtual ICollection<Recomendacion> Recomendacion { get; set; } = new List<Recomendacion>();

    public virtual ICollection<RiesgoIndicador> RiesgoIndicador { get; set; } = new List<RiesgoIndicador>();
}