// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Models;

public partial class IntentosInicioSesion
{
    public int IdIntentosInicioSesion { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<AdvanceIoc> AdvanceIoc { get; set; } = new List<AdvanceIoc>();
}