// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Models;

public partial class PaisInstitucion
{
    public int IdPaisInstitucion { get; set; }

    public int? IdPais { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<Incidente> Incidente { get; set; } = new List<Incidente>();
}