// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Models;

public partial class PrincipalIoc
{
    public long IdPrincipalIoc { get; set; }

    public int? IdIncidente { get; set; }

    public string DireccionIp { get; set; }

    public string ServidorIp { get; set; }

    public string DireccionWeb { get; set; }

    public string Dominio { get; set; }

    public string Hashes { get; set; }

    public string ArchivoSo { get; set; }

    public string ArchivoDocumento { get; set; }

    public string NombrePs { get; set; }

    public bool Activo { get; set; }

    public virtual Incidente IdIncidenteNavigation { get; set; }
}