// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Models;

public partial class Recomendacion
{
    public long IdRecomendacion { get; set; }

    public int IdIncidente { get; set; }

    public string Recomendacion1 { get; set; }

    public bool Activo { get; set; }

    public virtual Incidente IdIncidenteNavigation { get; set; }
}