// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConcentratorFraud.DataAccess.Models;

public partial class TipoIncidente
{
    public int IdTipoIncidente { get; set; }

    public string Descripcion { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<CategoriaIncidente> CategoriaIncidente { get; set; } = new List<CategoriaIncidente>();

    public virtual ICollection<Incidente> Incidente { get; set; } = new List<Incidente>();
}